stages:
  - precommit
  - build
  - publish
  - release

variables:
  PACKAGE_FILE: "bootscript"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic"

include:
  - project: "DevOps/gitlab-ci/job-templates/precommit"
    ref: a549cf5c2df7a206f2c3c644f5fe6e6dac638345
    file: ".gitlab-ci.yml"

.default:
  interruptible: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
      variables:
        PACKAGE_VERSION: ${CI_COMMIT_SHORT_SHA}
    - if: $CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-.*)?$/
      variables:
        PACKAGE_VERSION: ${CI_COMMIT_TAG}

🚸 precommit:
  extends:
    - .precommit
    - .default

🛠️ build:
  stage: build
  extends: .default
  image: golang:1.23@sha256:2fe82a3f3e006b4f2a316c6a21f62b66e1330ae211d039bb8d1128e12ed57bf1
  script:
    - go mod download
    - go build -o $PACKAGE_FILE
    - sha256sum "$PACKAGE_FILE" > "${PACKAGE_FILE}.sha256"
  artifacts:
    paths:
      - $PACKAGE_FILE
      - ${PACKAGE_FILE}.sha256
  rules:
    - changes:
        - "**/*.go"
        - "**/*.mod"
        - "**/*.sum"

🚀 publish:
  stage: publish
  extends: .default
  rules:
    - changes:
        - "**/*.go"
        - "**/*.mod"
        - "**/*.sum"
  image: registry.gitlab.com/gitlab-ci-utils/curl-jq:3.0.4@sha256:51b1d34e833d541c3e7d4e5141c670e896ce8b9d110a0ca4b93c2fedc6c3d4b7
  script:
    # Push the package to the GitLab Packages registry
    - |
      echo -e "\n\033[1;33mUploading package file: ${PACKAGE_FILE} to ${PACKAGE_REGISTRY_URL}/${PACKAGE_FILE}/${PACKAGE_VERSION}/${PACKAGE_FILE}\033[0m"
      curl -s --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${CI_PROJECT_DIR}/${PACKAGE_FILE} "${PACKAGE_REGISTRY_URL}/${PACKAGE_FILE}/${PACKAGE_VERSION}/${PACKAGE_FILE}"
      if [ $? -eq 0 ]; then
        echo -e "\n\033[1;32mUpload of ${PACKAGE_FILE} succeeded\033[0m"
      else
        echo -e "\n\033[1;31mUpload of ${PACKAGE_FILE} failed\033[0m"
      fi
    # Push the package checksum to the GitLab Packages registry
    - |
      echo -e "\n\033[1;33mUploading package signature: ${PACKAGE_FILE}.sha256 to ${PACKAGE_REGISTRY_URL}/${PACKAGE_FILE}.sha256/${PACKAGE_VERSION}/${PACKAGE_FILE}.sha256\033[0m"
      curl -s --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${CI_PROJECT_DIR}/${PACKAGE_FILE}.sha256 "${PACKAGE_REGISTRY_URL}/${PACKAGE_FILE}.sha256/${PACKAGE_VERSION}/${PACKAGE_FILE}.sha256"
      if [ $? -eq 0 ]; then
        echo -e "\n\033[1;32mUpload of ${PACKAGE_FILE}.sha256 succeeded\033[0m"
      else
        echo -e "\n\033[1;31mUpload of ${PACKAGE_FILE}.sha256 failed\033[0m"
      fi

📝 release:
  stage: release
  extends: .default
  image: registry.gitlab.com/gitlab-org/release-cli:v0.20.0@sha256:0cc9957c237cafd4bb6dc553c879a811787ccbc6bbf21d64fd7a5849a8d633ae
  rules:
    - if: $CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
      variables:
        PACKAGE_VERSION: ${CI_COMMIT_TAG}
    - changes:
        - "**/*.go"
        - "**/*.mod"
        - "**/*.sum"
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${PACKAGE_FILE}\",\"filepath\":\"/${PACKAGE_FILE}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_FILE}/${PACKAGE_VERSION}/${PACKAGE_FILE}\",\"link_type\": \"package\"}" \
        --assets-link "{\"name\":\"${PACKAGE_FILE}.sha256\",\"filepath\":\"/${PACKAGE_FILE}.sha256\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_FILE}.sha256/${PACKAGE_VERSION}/${PACKAGE_FILE}.sha256\",\"link_type\": \"package\"}"
