#!/bin/sh

BOLDRED="\e[1;31m"
BOLDGREEN="\e[1;32m"
BOLDCYAN="\e[38;2;95;135;255m"
BOLDMAGENTA="\e[1;35m"
BOLDRED="\e[1;31m"
BOLDORANGE="\e[1;38;2;255;165;0m"
ENDCOLOR="\e[0m"
export ARCHAVISTO_VERSION="2.1.0"

set -e
trap handle_error ERR

handle_error() {
	echo -e "${BOLDRED}/!\\ Something went wrong! Exiting... ${ENDCOLOR}"
	echo -e "${BOLDGREEN}Fill in a ticket on https://support.advans-group.com or contact maintainers on Teams.${ENDCOLOR}"
	sudo rm -rf /opt/startup/bootscript /opt/startup/bootscript.sha256 /opt/startup/script.sh
	exit 1
}

# gitlab_token must be present on the wsl image
export GITLAB_TOKEN=$(cat /opt/startup/gitlab_token)

# Get the binary and its checksum
# If you want to use direct link to a specific version, copy the links from the pipeline (publish job) or replace by "https://versioning.advans-group.com/api/v4/projects/1495/packages/generic/bootscript/<version>/bootscript"

echo -e "${BOLDCYAN}Downloading the bootscript...${ENDCOLOR}"
curl --location --output /opt/startup/bootscript \
	--header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
	"https://versioning.advans-group.com/api/v4/projects/1495/releases/permalink/latest/downloads/bootscript"

curl --location --output /opt/startup/bootscript.sig \
	--header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
	"https://versioning.advans-group.com/api/v4/projects/1495/releases/permalink/latest/downloads/bootscript.sha256"

echo -e "${BOLDCYAN}Verifying integrity...${ENDCOLOR}"

if sha256sum --check bootscript.sha256 >/dev/null 2>&1; then
	echo -e "${BOLDRED}[ERROR] integrity verification failed. Exiting...${ENDCOLOR}"
	exit 1
fi
echo -e "${BOLDGREEN}Binary integrity verified successfully${ENDCOLOR}"
chmod +x /opt/startup/bootscript

sudo sed -i "s/^PRETTY_NAME=.*/PRETTY_NAME=\"Arch Avisto v${ARCHAVISTO_VERSION}\"/" /etc/os-release

/opt/startup/bootscript
/opt/startup/script.sh

echo -e "${BOLDGREEN}Installation complete${ENDCOLOR}"
echo -e "${BOLDORANGE}[WARNING] Now you must restart WSL using the commands ${BOLDRED}wsl -t <distro-name> ${BOLDORANGE}and then ${BOLDRED}wsl -d <distro-name>${ENDCOLOR}"
