name: Build Pipeline

on:
  push:
    branches:
      - main # Or your default branch
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
    paths:
      - "**/*.go"
      - "**/*.mod"
      - "**/*.sum"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main # Or your default branch
    paths:
      - "**/*.go"
      - "**/*.mod"
      - "**/*.sum"
  workflow_dispatch:

env:
  PACKAGE_FILE: "bootscript"
  PACKAGE_CHECKSUM: "bootscript.sha256"

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: precommit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Get dependencies
        run: go mod download
      - name: Build
        run: go build -o ${{ env.PACKAGE_FILE }}
      - name: Generate checksum
        run: sha256sum "${{ env.PACKAGE_FILE }}" > "${{ env.PACKAGE_CHECKSUM }}"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: |
            ${{ env.PACKAGE_FILE }}
            ${{ env.PACKAGE_CHECKSUM }}
